version: "3"

services: 
    app:
        container_name: paw_app
        build:
            context: .
            dockerfile: Dockerfile
        volumes: 
            - "./:/usr/src/app"
        ports: 
            - 8888:8888
        command: ["bash", "runserver.sh"]

    db:
        container_name: paw_db
        image: postgres:12
        restart: unless-stopped
        volumes:
            - postgres-data:/var/lib/postgresql/data
        ports:
            - "${DB_PORT-5432}:5432"
        environment:
            POSTGRES_DB: ${DB_DBNAME}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
    
    pgadmin:
        container_name: paw_pgadmin
        image: dpage/pgadmin4:5.3
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
            PGADMIN_LISTEN_PORT: ${PGADMIN_LISTEN_PORT}
        ports:
            - "${PGADMIN_PORT-5000}:${PGADMIN_LISTEN_PORT}"

networks:
    paw_default:
        external: true

volumes:
    postgres-data: {}