version: "3"

services: 
    app:
        container_name: paw_app
        build:
            context: .
            dockerfile: Dockerfile
        volumes: 
            - "./:/usr/src/app"
        ports: 
            - 8888:8888
        command: ["bash", "../runserver.sh"]

    db:
        container_name: paw_db
        image: postgres:12
        restart: unless-stopped
        volumes:
            - postgres-data:/var/lib/postgresql/data
        ports:
            - 54322:5432
        environment:
            POSTGRES_DB: paw
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admin

volumes:
    postgres-data: {}